buff_tracker:
  ros__parameters:
    val_CUDA_ARMOR_THRESHOLD: 45  #50
    val_CUDA_ARMOR_THRESHOLD_RED: 0.9
    val_CUDA_ARMOR_THRESHOLD_GREEN: 0.1
    val_CUDA_ARMOR_THRESHOLD_BLUE: 0.0
    val_CUDA_ARROW_THRESHOLD: 55 #204
    val_CUDA_ARROW_THRESHOLD_RED: 0.9
    val_CUDA_ARROW_THRESHOLD_GREEN: 0.1
    val_CUDA_ARROW_THRESHOLD_BLUE: 0.0
    val_LOCAL_ROI_DISTANCE_RATIO: 1.2
    val_MAX_ARROW_LIGHTLINE_ASPECT_RATIO: 3.0
    val_MAX_ARROW_LIGHTLINE_AREA: 6000.0
    val_MIN_ARROW_LIGHTLINE_AREA: 30.0 #1500
    val_GLOBAL_ROI_LENGTH_RATIO: 1.4
    val_MAX_ARMOR_TARGETSHAPE_CONTOUR_AREA: 100000.0
    val_MIN_ARMOR_TARGETSHAPE_CONTOUR_AREA: 800.0 #3000.0
    val_MAX_ARMOR_TARGETSHAPE_ASPECT_RATIO: 3.7
    val_MIN_ARMOR_TARGETSHAPE_ASPECT_RATIO: 1.0
    val_MIN_ARMOR_TARGETSHAPE_CHILDREN_NUM: 4
    val_MAX_ARMOR_TARGETSHAPE_CHILDREN_NUM: 10
    val_MIN_ARROW_LIGHTLINE_NUM: 3
    val_MAX_ARROW_LIGHTLINE_NUM: 13
    val_MIN_ARMOR_TARGETSHAPE_AREA: 5000.0
    val_MAX_ARMOR_TARGETSHAPE_AREA: 40000.0
    val_MIN_CENTER_AREA: 50.0
    val_MAX_CENTER_AREA: 6000.0
    val_MAX_CENTER_ASPECT_RATIO: 2.0
    val_MIN_ARROW_ASPECT_RATIO: 2.0
    val_MAX_ARROW_ASPECT_RATIO: 12.0
    val_MAX_ARROW_AREA: 25000.0
    val_LOCAL_ROI_LENTH: 200.0
    val_DELTA_TIME: 0.2
    
rm_serial:
  ros__parameters:
    baudrate: 115200
    bytesize: 8
    flowcontrol: 0
    tc.v0: 30.0
    tc.gyro_thresold: 1.57079632679
    tc.time_delta: -0.5
    tc.amy: 0.785398163397
    parity: 0
    port: /dev/ttyACM0 # USB0 - USB-TTL, # THS0 - 串口直连, # ACM0 - USB直连
    stopbits: 1
    timeout: 500

camera:
  ros__parameters:
    analog_gain: 0.0
    camera_info_url: package://daheng_camera/config/camera_info.yaml
    camera_name: dxi_camera
    cvtype: 0
    exposure_time: 3000.0 #3000
    flip: false
    fps: 100.0
    use_sensor_data_qos: false
    use_trigger: -1
gimbal_description:
  ros__parameters:
    robot: "rm_gimbal"
